version: 0.2

env:
  parameter-store:
    TWINE_USERNAME: /CodeBuild/pypi-user
    TWINE_PASSWORD: /CodeBuild/pypi-password
    GITHUB_TOKEN: /CodeBuild/GITHUB_TOKEN
  variables:
    CODE_VERSION: 0.2

phases:
  build:
    commands:
      - pip install --upgrade setuptools wheel twine
      - mkdir -p sceptre-aws-resolver/sceptre-aws-resolver
      - cp main.py setup.py README.md release.sh sceptre-aws-resolver/
      - cd sceptre-aws-resolver && ./release.sh
